import { registerTheme, SoribashiProvider } from '@soribashi/core';
import { uiTheme } from '@soribashi/ui';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
// The theme CSS is the ui package's artifact, imported through its export map
// (SORI-13); only the tenant demo's CSS is generated by, and lives in, this app.
import '@soribashi/ui/theme.css';
import { App } from './App.tsx';
import './generated/tenants.css';
import './styles.css';

const container = document.getElementById('root');
if (!container) {
  throw new Error('workshop: #root element not found');
}

// create-builders.ts documents the split: `makeBuilders`/builders carry no
// runtime registerTheme call themselves, so the app entry must call it once,
// which is what turns on dev-time vocabulary validation for every builder
// that reads from this theme.
registerTheme(uiTheme);

createRoot(container).render(
  <StrictMode>
    <SoribashiProvider theme={uiTheme}>
      <App />
    </SoribashiProvider>
  </StrictMode>,
);
