import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const gen = (f: string) => readFileSync(join(__dirname, 'generated', f), 'utf-8');

describe('codegen v4 outputs (committed, regenerated by codegen:shadcn-starter)', () => {
  it('tailwind.css is a v4 @theme block carrying the token vars', () => {
    const css = gen('tailwind.css');
    expect(css).toContain('@theme {');
    expect(css).toContain('--color-primary-500:');
    expect(css).toContain('--color-neutral-500:');
    expect(css).toContain('--radius-md:');
  });

  it('theme.css carries semantic vars, dark block, and component dimensions', () => {
    const css = gen('theme.css');
    expect(css).toContain(':root {');
    expect(css).toContain('--text-default:');
    expect(css).toContain('--surface-canvas:');
    expect(css).toContain('.dark {');
    expect(css).toContain('--button-height-md: 2.25rem;');
  });

  it('theme.css re-declares --surface-canvas inside .dark so wrapper-scoped dark mode flips it', () => {
    const css = gen('theme.css');
    const darkBlock = css.slice(css.indexOf('.dark {'));
    expect(darkBlock).toContain('--surface-canvas:');
  });

  it('v4-only setup skips the --__hsl- companion namespace', () => {
    expect(gen('theme.css')).not.toContain('--__hsl-');
  });
});
