// @soribashi/core — the published barrel: one import for the component
// factory's builders and the theme model. Framework only, no components.

export type {
  BoxStyleProps,
  ComponentExtendConfig,
  DefineCompoundConfig,
  InlineStylesProps,
  MergedRefCallback,
  ParsedStyleProps,
  PartConfig,
  PartRenderCtx,
  PolymorphicPartConfig,
  PolymorphicPartRenderCtx,
  PolymorphicProps,
  PolymorphicRef,
  PolymorphicRenderCtx,
  RecipeMeta,
  StandardPartConfig,
  StyleProp,
  StylePropDefinition,
  StylesApiProps,
  UniversalStyleProps,
  UseStylePropsResult,
  VocabularyOverride,
} from './factory/index.ts';
export {
  autoVars,
  cn,
  configureClassNameMerge,
  createSoribashiBuilders,
  defineComponent,
  defineCompound,
  defineGenericComponent,
  definePolymorphicComponent,
  extractStyleProps,
  getFontSize,
  getLineHeight,
  getRadius,
  getRecipeMeta,
  getShadow,
  getSize,
  getSpacing,
  getThemeColor,
  InlineStyles,
  isDev,
  makeBuilders,
  mergeRefs,
  parseStyleProps,
  registerTheme,
  rem,
  SoribashiProvider,
  STYLE_PROPS_DATA,
  useRandomClassName,
  useStyleProps,
  useTheme,
} from './factory/index.ts';
export type {
  ColorScale,
  ComponentThemeConfig,
  IntentResolver,
  IntentResolverInput,
  IntentResolverResult,
  PartialThemeTokens,
  ResolvedTheme,
  SemanticTokensConfig,
  ThemeComponentEntry,
  ThemeDefinition,
  ThemeTokens,
  Vocabulary,
} from './theme/index.ts';
export {
  composeTheme,
  createTheme,
  defaultDarkTokens,
  defaultIntentResolver,
  defaultTokens,
  defineVocabulary,
  isThemeComponentEntry,
  rampVariantColors,
} from './theme/index.ts';
