import type { ResolvedTheme } from '@soribashi/theme';

const HEADER = `/* auto-generated by @soribashi/codegen — do not edit manually */`;

/**
 * Emits a Tailwind v3 config snippet that maps token names to CSS variables.
 *
 * Color families use the `<alpha-value>` pattern so utility classes like
 * `bg-primary-500/50` work correctly.
 */
export function emitTailwindV3(theme: ResolvedTheme): string {
  const lines: string[] = [HEADER, ''];
  lines.push('module.exports = {');
  lines.push('  theme: {');

  if (Object.keys(theme.tokens.colors).length > 0) {
    lines.push('    colors: {');
    const families = Object.entries(theme.tokens.colors).sort(byKey);
    for (const [family, scale] of families) {
      lines.push(`      ${family}: {`);
      const shades = Object.entries(scale).sort(byKey);
      for (const [shade, _] of shades) {
        // Use the bare-component companion var (`--__hsl-color-` prefix) so
        // Tailwind's `<alpha-value>` substitution produces valid CSS. The
        // canonical wrapped var (`--color-${family}-${shade}`) remains for
        // direct CSS use. The `--__hsl-` prefix keeps companion vars out of
        // the `--color-` autocomplete namespace (typing `--color-` only
        // surfaces canonical wrapped vars).
        lines.push(
          `        '${shade}': 'hsl(var(--__hsl-color-${family}-${shade}) / <alpha-value>)',`,
        );
      }
      lines.push('      },');
    }
    lines.push('    },');
  }

  emitVarMap(lines, theme.tokens.radius, 'borderRadius', 'radius', 4);
  emitVarMap(lines, theme.tokens.spacing, 'spacing', 'spacing', 4);
  emitVarMap(lines, theme.tokens.fontSize, 'fontSize', 'font-size', 4);

  if (theme.tokens.fontFamily) {
    emitVarMap(lines, theme.tokens.fontFamily, 'fontFamily', 'font-family', 4);
  }

  if (theme.tokens.fontWeight) {
    emitVarMap(lines, theme.tokens.fontWeight, 'fontWeight', 'font-weight', 4);
  }

  if (theme.tokens.lineHeight) {
    emitVarMap(lines, theme.tokens.lineHeight, 'lineHeight', 'line-height', 4);
  }

  if (theme.tokens.shadow) {
    emitVarMap(lines, theme.tokens.shadow, 'boxShadow', 'shadow', 4);
  }

  if (theme.tokens.zIndex) {
    emitVarMap(lines, theme.tokens.zIndex, 'zIndex', 'z-index', 4);
  }

  if (theme.tokens.breakpoint) {
    lines.push('    screens: {');
    const entries = Object.entries(theme.tokens.breakpoint).sort(byKey);
    for (const [key, value] of entries) {
      lines.push(`      ${quoteIfNeeded(key)}: '${value}',`);
    }
    lines.push('    },');
  }

  lines.push('  },');
  lines.push('};');

  return `${lines.join('\n')}\n`;
}

function emitVarMap(
  lines: string[],
  source: Record<string, string | number>,
  configKey: string,
  varPrefix: string,
  indent: number,
): void {
  if (Object.keys(source).length === 0) return;
  const pad = ' '.repeat(indent);
  lines.push(`${pad}${configKey}: {`);
  const entries = Object.entries(source).sort(byKey);
  for (const [key, _] of entries) {
    lines.push(`${pad}  ${quoteIfNeeded(key)}: 'var(--${varPrefix}-${key})',`);
  }
  lines.push(`${pad}},`);
}

function quoteIfNeeded(key: string): string {
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key)) return key;
  return `'${key}'`;
}

function byKey([a]: [string, unknown], [b]: [string, unknown]): number {
  return a.localeCompare(b);
}
