import type { ResolvedTheme } from '@soribashi/theme';

const HEADER = '/* auto-generated by @soribashi/codegen — do not edit manually */';

/**
 * Tailwind v4's default `--container-*` key set (taken from tailwindcss 4.3.2
 * `theme.css`).
 *
 * These names are the collision surface for theme spacing tokens. Tailwind's
 * sizing utilities — `w-`, `h-`, `min-w-`, `max-w-`, `min-h-`, `max-h-`,
 * `size-`, `basis-` — consult `--spacing-*` BEFORE `--container-*`, and
 * `--spacing-*` wins unconditionally. Declaration order does not change it and
 * `--spacing-*: initial` does not restore it, so emitting `--spacing-sm`
 * silently redefines `max-w-sm` from 24rem to the spacing value. The failure is
 * invisible: the utility still compiles, it just resolves to a few pixels.
 */
const TAILWIND_V4_CONTAINER_KEYS: ReadonlySet<string> = new Set([
  '3xs',
  '2xs',
  'xs',
  'sm',
  'md',
  'lg',
  'xl',
  '2xl',
  '3xl',
  '4xl',
  '5xl',
  '6xl',
  '7xl',
]);

/**
 * How theme spacing tokens map onto Tailwind v4's `--spacing-*` namespace.
 *
 *   'safe' — withhold keys that collide with the `--container-*` scale, so the
 *            sizing utilities keep Tailwind's meaning. Non-colliding keys are
 *            emitted normally, so a theme spacing key named `cozy` still yields
 *            `p-cozy`.
 *   'all'  — emit every key. Named spacing utilities work for the full scale,
 *            at the cost of the sizing utilities on the colliding names.
 */
export type SpacingUtilitiesMode = 'safe' | 'all';

export interface EmitTailwindV4Options {
  /**
   * Spacing-namespace policy. @default 'safe'
   *
   * Vocabulary stays theme-declared either way (invariant 2): this governs
   * which Tailwind namespace the emitter writes into, not what the values are.
   */
  spacingUtilities?: SpacingUtilitiesMode;
}

/**
 * Emits a Tailwind v4 `@theme` block from the soribashi theme.
 *
 * In Tailwind v4, CSS is the source of truth for tokens — utility classes
 * are generated automatically from `@theme { --color-xxx: ...; }` blocks.
 */
export function emitTailwindV4(theme: ResolvedTheme, opts: EmitTailwindV4Options = {}): string {
  const spacingMode: SpacingUtilitiesMode = opts.spacingUtilities ?? 'safe';
  const lines: string[] = [HEADER, ''];
  lines.push('@theme {');

  for (const [family, scale] of Object.entries(theme.tokens.colors).sort(byKey)) {
    for (const [shade, value] of Object.entries(scale).sort(byKey)) {
      lines.push(`  --color-${family}-${shade}: ${value};`);
    }
  }

  for (const [key, value] of Object.entries(theme.tokens.radius).sort(byKey)) {
    lines.push(`  --radius-${key}: ${value};`);
  }

  const spacing = Object.entries(theme.tokens.spacing).sort(byKey);
  const shadowing = spacing.filter(([key]) => TAILWIND_V4_CONTAINER_KEYS.has(key));
  const emitted =
    spacingMode === 'all'
      ? spacing
      : spacing.filter(([key]) => !TAILWIND_V4_CONTAINER_KEYS.has(key));

  for (const [key, value] of emitted) {
    lines.push(`  --spacing-${key}: ${value};`);
  }

  if (shadowing.length > 0) {
    const keys = shadowing.map(([key]) => key).join(', ');
    if (spacingMode === 'all') {
      console.warn(
        `[soribashi] spacingUtilities: 'all' emitted --spacing-* for ${keys}, which shadow Tailwind's --container-* scale. The sizing utilities on those names (max-w-, w-, min-w-, size-, basis-) now resolve to the spacing values instead of the container widths. For example max-w-md becomes ${shadowing.find(([k]) => k === 'md')?.[1] ?? 'the md spacing value'} rather than 28rem. Use arbitrary values (max-w-[28rem]) for sizing, or drop back to 'safe'.`,
      );
    } else {
      // Discoverability without console noise: 'safe' is the correct default
      // doing its job, so it stays quiet, but the generated file is where
      // someone chasing "why doesn't p-md exist?" will actually look.
      const example = shadowing[0]?.[0];
      lines.push(
        `  /* Withheld from --spacing-*: ${keys}. These keys collide with Tailwind's --container-* scale,`,
        '     and --spacing-* wins for max-w-/w-/min-w-/size-/basis-, which would silently shrink them.',
        `     The values are still emitted into theme.css, so p-(--spacing-${example}) works. Set`,
        "     output.tailwind.spacingUtilities: 'all' to emit them as utilities anyway. */",
      );
    }
  }

  for (const [key, value] of Object.entries(theme.tokens.fontSize).sort(byKey)) {
    lines.push(`  --text-${key}: ${value};`);
  }

  if (theme.tokens.fontFamily) {
    for (const [key, value] of Object.entries(theme.tokens.fontFamily).sort(byKey)) {
      lines.push(`  --font-${key}: ${value};`);
    }
  }

  if (theme.tokens.fontWeight) {
    for (const [key, value] of Object.entries(theme.tokens.fontWeight).sort(byKey)) {
      lines.push(`  --font-weight-${key}: ${value};`);
    }
  }

  if (theme.tokens.lineHeight) {
    for (const [key, value] of Object.entries(theme.tokens.lineHeight).sort(byKey)) {
      lines.push(`  --leading-${key}: ${value};`);
    }
  }

  if (theme.tokens.shadow) {
    for (const [key, value] of Object.entries(theme.tokens.shadow).sort(byKey)) {
      lines.push(`  --shadow-${key}: ${value};`);
    }
  }

  if (theme.tokens.breakpoint) {
    for (const [key, value] of Object.entries(theme.tokens.breakpoint).sort(byKey)) {
      lines.push(`  --breakpoint-${key}: ${value};`);
    }
  }

  if (theme.tokens.zIndex) {
    // Not an official v4 theme namespace; the vars still land in the compiled
    // CSS and are usable via arbitrary values like `z-(--z-index-modal)`.
    for (const [key, value] of Object.entries(theme.tokens.zIndex).sort(byKey)) {
      lines.push(`  --z-index-${key}: ${value};`);
    }
  }

  lines.push('}');

  return `${lines.join('\n')}\n`;
}

function byKey([a]: [string, unknown], [b]: [string, unknown]): number {
  return a.localeCompare(b);
}
