import type {
  PartialThemeTokens,
  ResolvedTheme,
  SemanticSurfaceValue,
  ThemeTokens,
} from '@soribashi/theme';
import { removeDefaultVariables } from './remove-default-variables.ts';
import type { EmitCssOptions } from './types.ts';

const HEADER = '/* auto-generated by @soribashi/codegen — do not edit manually */';

/**
 * Emits the soribashi theme as a CSS file with custom properties for the
 * configured scope and dark mode selectors.
 */
export function emitCss(theme: ResolvedTheme, opts: EmitCssOptions = {}): string {
  const effectiveTheme = opts.removeDefaultVariables ? removeDefaultVariables(theme) : theme;
  const additions = opts.cssVariablesResolver
    ? opts.cssVariablesResolver(effectiveTheme)
    : undefined;

  if (opts.removeDefaultVariables) {
    const removed = countEmittedTokenVars(theme) - countEmittedTokenVars(effectiveTheme);
    if (removed > 0) {
      // Nothing in soribashi ships a baseline stylesheet (no equivalent of
      // @mantine/core/styles.css), so deduped output is broken unless the
      // consumer provides one. Warn loudly until that story exists.
      console.warn(
        `[soribashi] removeDefaultVariables removed ${removed} variable(s) that match the soribashi defaults. The generated CSS is NOT self-contained: a baseline stylesheet defining the soribashi default variables must be loaded before it, or the removed variables will be undefined at runtime.`,
      );
    }
  }

  const lines: string[] = [HEADER, ''];

  // :root block
  lines.push(`${effectiveTheme.scope} {`);
  lines.push('  color-scheme: light;');
  emitTokenLines(lines, effectiveTheme.tokens, effectiveTheme.dark);
  emitSemanticLines(lines, effectiveTheme);
  if (additions?.root) {
    for (const [key, value] of Object.entries(additions.root)) {
      lines.push(`  ${key}: ${value};`);
    }
  }
  lines.push('}');

  // Tokens carry both schemes via light-dark(), so the dark selector only has
  // to flip color-scheme. Re-emitting semantic vars here (which the previous
  // implementation required) is no longer necessary: light-dark() resolves at
  // the point of use, so a scoped wrapper flips without any restatement.
  lines.push('');
  lines.push(`${effectiveTheme.darkMode.selector} {`);
  lines.push('  color-scheme: dark;');
  if (additions?.dark) {
    for (const [key, value] of Object.entries(additions.dark)) {
      lines.push(`  ${key}: ${value};`);
    }
  }
  lines.push('}');

  // Optional scopes — flat blocks for each scope name
  if (additions?.scopes) {
    for (const [scopeName, scopeVars] of Object.entries(additions.scopes)) {
      if (scopeVars.root && Object.keys(scopeVars.root).length > 0) {
        lines.push('');
        lines.push(`${scopeName} {`);
        for (const [key, value] of Object.entries(scopeVars.root)) {
          lines.push(`  ${key}: ${value};`);
        }
        lines.push('}');
      }
      if (scopeVars.dark && Object.keys(scopeVars.dark).length > 0) {
        lines.push('');
        lines.push(`${effectiveTheme.darkMode.selector} ${scopeName} {`);
        for (const [key, value] of Object.entries(scopeVars.dark)) {
          lines.push(`  ${key}: ${value};`);
        }
        lines.push('}');
      }
    }
  }

  return `${lines.join('\n')}\n`;
}

function countEmittedTokenVars(theme: ResolvedTheme): number {
  const scratch: string[] = [];
  emitTokenLines(scratch, theme.tokens, theme.dark);
  return scratch.length;
}

/**
 * Pairs a light value with its dark override. Unregistered custom properties
 * substitute lazily, so light-dark() resolves against the color-scheme of the
 * element that USES the var, not the one that declares it. That is what lets a
 * single declaration serve a scoped dark wrapper, and it is why colour tokens
 * must never be registered via @property (see emit-property.ts).
 */
function pairValue(light: string, dark: string | undefined): string {
  return dark === undefined ? light : `light-dark(${light}, ${dark})`;
}

function emitTokenLines(lines: string[], tokens: ThemeTokens, dark: PartialThemeTokens): void {
  for (const [family, scale] of Object.entries(tokens.colors).sort(byKey)) {
    for (const [shade, value] of Object.entries(scale).sort(byKey)) {
      const darkValue = dark.colors?.[family]?.[shade];
      lines.push(`  --color-${family}-${shade}: ${pairValue(value, darkValue)};`);
    }
  }

  for (const [key, value] of Object.entries(tokens.radius).sort(byKey)) {
    lines.push(`  --radius-${key}: ${pairValue(value, dark.radius?.[key])};`);
  }

  for (const [key, value] of Object.entries(tokens.spacing).sort(byKey)) {
    lines.push(`  --spacing-${key}: ${pairValue(value, dark.spacing?.[key])};`);
  }

  for (const [key, value] of Object.entries(tokens.fontSize).sort(byKey)) {
    lines.push(`  --font-size-${key}: ${pairValue(value, dark.fontSize?.[key])};`);
  }

  if (tokens.fontFamily) {
    for (const [key, value] of Object.entries(tokens.fontFamily).sort(byKey)) {
      lines.push(`  --font-family-${key}: ${pairValue(value, dark.fontFamily?.[key])};`);
    }
  }

  if (tokens.fontWeight) {
    for (const [key, value] of Object.entries(tokens.fontWeight).sort(byKey)) {
      lines.push(`  --font-weight-${key}: ${pairValue(value, dark.fontWeight?.[key])};`);
    }
  }

  if (tokens.lineHeight) {
    for (const [key, value] of Object.entries(tokens.lineHeight).sort(byKey)) {
      lines.push(`  --line-height-${key}: ${pairValue(value, dark.lineHeight?.[key])};`);
    }
  }

  if (tokens.shadow) {
    for (const [key, value] of Object.entries(tokens.shadow).sort(byKey)) {
      lines.push(`  --shadow-${key}: ${pairValue(value, dark.shadow?.[key])};`);
    }
  }

  if (tokens.breakpoint) {
    for (const [key, value] of Object.entries(tokens.breakpoint).sort(byKey)) {
      lines.push(`  --breakpoint-${key}: ${pairValue(value, dark.breakpoint?.[key])};`);
    }
  }

  if (tokens.zIndex) {
    for (const [key, value] of Object.entries(tokens.zIndex).sort(byKey)) {
      const darkValue = dark.zIndex?.[key];
      lines.push(
        `  --z-index-${key}: ${pairValue(String(value), darkValue === undefined ? undefined : String(darkValue))};`,
      );
    }
  }

  if (tokens.heading) {
    const darkHeading = dark.heading;
    if (tokens.heading.textWrap !== undefined) {
      lines.push(
        `  --heading-text-wrap: ${pairValue(tokens.heading.textWrap, darkHeading?.textWrap)};`,
      );
    }
    for (const [order, size] of Object.entries(tokens.heading.sizes).sort(byKey)) {
      const darkSize = darkHeading?.sizes?.[order as keyof typeof tokens.heading.sizes];
      lines.push(
        `  --heading-${order}-font-size: ${pairValue(size.fontSize, darkSize?.fontSize)};`,
      );
      if (size.fontWeight !== undefined) {
        lines.push(
          `  --heading-${order}-font-weight: ${pairValue(size.fontWeight, darkSize?.fontWeight)};`,
        );
      }
      if (size.lineHeight !== undefined) {
        lines.push(
          `  --heading-${order}-line-height: ${pairValue(size.lineHeight, darkSize?.lineHeight)};`,
        );
      }
    }
  }
}

function emitSemanticLines(lines: string[], theme: ResolvedTheme): void {
  for (const [key, ref] of Object.entries(theme.semanticTokens.text).sort(byKey)) {
    lines.push(`  --text-${key}: ${semanticToVar(ref)};`);
  }

  for (const [key, raw] of Object.entries(theme.semanticTokens.surface).sort(byKey)) {
    const pair = resolveSurfacePair(raw);
    lines.push(`  --surface-${key}: ${semanticToVar(pair.value)};`);
    if (pair.foreground !== undefined) {
      lines.push(`  --surface-${key}-foreground: ${semanticToVar(pair.foreground)};`);
    }
  }

  for (const [key, ref] of Object.entries(theme.semanticTokens.border).sort(byKey)) {
    lines.push(`  --border-${key}: ${semanticToVar(ref)};`);
  }

  if (theme.semanticTokens.accent) {
    for (const [key, ref] of Object.entries(theme.semanticTokens.accent).sort(byKey)) {
      lines.push(`  --accent-${key}: ${semanticToVar(ref)};`);
    }
  }
}

interface SurfacePair {
  value: string;
  foreground?: string;
}

function resolveSurfacePair(raw: SemanticSurfaceValue): SurfacePair {
  if (typeof raw === 'string') {
    return { value: raw };
  }
  return {
    value: raw.value,
    foreground: raw.foreground,
  };
}

function semanticToVar(ref: string): string {
  // 'colors.neutral.500' -> 'var(--color-neutral-500)'
  // 'radius.md' -> 'var(--radius-md)'
  const parts = ref.split('.');
  if (parts[0] === 'colors' && parts.length === 3) {
    return `var(--color-${parts[1]}-${parts[2]})`;
  }
  if (parts[0] === 'radius' && parts.length === 2) {
    return `var(--radius-${parts[1]})`;
  }
  if (parts[0] === 'spacing' && parts.length === 2) {
    return `var(--spacing-${parts[1]})`;
  }
  if (parts[0] === 'fontSize' && parts.length === 2) {
    return `var(--font-size-${parts[1]})`;
  }
  return ref;
}

function byKey([a]: [string, unknown], [b]: [string, unknown]): number {
  return a.localeCompare(b);
}
