import type { ResolvedTheme, ThemeTokens, PartialThemeTokens } from '@soribashi/theme';
import type { EmitCssOptions } from './types.ts';
import { removeDefaultVariables } from './remove-default-variables.ts';

const HEADER = `/* auto-generated by @soribashi/codegen — do not edit manually */`;

/**
 * Emits the soribashi theme as a CSS file with custom properties for the
 * configured scope and dark mode selectors.
 */
export function emitCss(theme: ResolvedTheme, opts: EmitCssOptions = {}): string {
  const effectiveTheme = opts.removeDefaultVariables ? removeDefaultVariables(theme) : theme;
  const additions = opts.cssVariablesResolver ? opts.cssVariablesResolver(effectiveTheme) : undefined;
  // 'auto' is treated as `true` at this layer; build.ts resolves 'auto' to a
  // concrete boolean before calling emitCss based on the Tailwind output mode.
  const emitCompanion = opts.emitCompanionHsl !== false;

  const lines: string[] = [HEADER, ''];

  // :root block
  lines.push(`${effectiveTheme.scope} {`);
  emitTokenLines(lines, effectiveTheme.tokens, emitCompanion);
  emitSemanticLines(lines, effectiveTheme);
  if (additions?.root) {
    for (const [key, value] of Object.entries(additions.root)) {
      lines.push(`  ${key}: ${value};`);
    }
  }
  lines.push('}');

  // .dark block — emitted if there are dark token overrides OR consumer dark vars
  const hasDarkTokens = Object.keys(effectiveTheme.dark).length > 0;
  const hasDarkAdditions = !!additions?.dark && Object.keys(additions.dark).length > 0;
  if (hasDarkTokens || hasDarkAdditions) {
    lines.push('');
    lines.push(`${effectiveTheme.darkMode.selector} {`);
    if (hasDarkTokens) emitDarkTokenLines(lines, effectiveTheme.dark, emitCompanion);
    if (additions?.dark) {
      for (const [key, value] of Object.entries(additions.dark)) {
        lines.push(`  ${key}: ${value};`);
      }
    }
    lines.push('}');
  }

  // Optional scopes — flat blocks for each scope name
  if (additions?.scopes) {
    for (const [scopeName, scopeVars] of Object.entries(additions.scopes)) {
      if (scopeVars.root && Object.keys(scopeVars.root).length > 0) {
        lines.push('');
        lines.push(`${scopeName} {`);
        for (const [key, value] of Object.entries(scopeVars.root)) {
          lines.push(`  ${key}: ${value};`);
        }
        lines.push('}');
      }
      if (scopeVars.dark && Object.keys(scopeVars.dark).length > 0) {
        lines.push('');
        lines.push(`${effectiveTheme.darkMode.selector} ${scopeName} {`);
        for (const [key, value] of Object.entries(scopeVars.dark)) {
          lines.push(`  ${key}: ${value};`);
        }
        lines.push('}');
      }
    }
  }

  return `${lines.join('\n')}\n`;
}

function emitTokenLines(
  lines: string[],
  tokens: ThemeTokens,
  emitCompanion: boolean,
): void {
  for (const [family, scale] of Object.entries(tokens.colors).sort(byKey)) {
    for (const [shade, value] of Object.entries(scale).sort(byKey)) {
      lines.push(`  --color-${family}-${shade}: ${value};`);
      if (emitCompanion) {
        const bare = stripHslWrapper(value);
        if (bare !== null) {
          lines.push(`  --__hsl-color-${family}-${shade}: ${bare};`);
        }
      }
    }
  }

  for (const [key, value] of Object.entries(tokens.radius).sort(byKey)) {
    lines.push(`  --radius-${key}: ${value};`);
  }

  for (const [key, value] of Object.entries(tokens.spacing).sort(byKey)) {
    lines.push(`  --spacing-${key}: ${value};`);
  }

  for (const [key, value] of Object.entries(tokens.fontSize).sort(byKey)) {
    lines.push(`  --font-size-${key}: ${value};`);
  }

  if (tokens.fontFamily) {
    for (const [key, value] of Object.entries(tokens.fontFamily).sort(byKey)) {
      lines.push(`  --font-family-${key}: ${value};`);
    }
  }

  if (tokens.fontWeight) {
    for (const [key, value] of Object.entries(tokens.fontWeight).sort(byKey)) {
      lines.push(`  --font-weight-${key}: ${value};`);
    }
  }

  if (tokens.lineHeight) {
    for (const [key, value] of Object.entries(tokens.lineHeight).sort(byKey)) {
      lines.push(`  --line-height-${key}: ${value};`);
    }
  }

  if (tokens.shadow) {
    for (const [key, value] of Object.entries(tokens.shadow).sort(byKey)) {
      lines.push(`  --shadow-${key}: ${value};`);
    }
  }

  if (tokens.breakpoint) {
    for (const [key, value] of Object.entries(tokens.breakpoint).sort(byKey)) {
      lines.push(`  --breakpoint-${key}: ${value};`);
    }
  }

  if (tokens.heading) {
    if (tokens.heading.textWrap !== undefined) {
      lines.push(`  --heading-text-wrap: ${tokens.heading.textWrap};`);
    }
    for (const [order, size] of Object.entries(tokens.heading.sizes).sort(byKey)) {
      lines.push(`  --heading-${order}-font-size: ${size.fontSize};`);
      if (size.fontWeight !== undefined) {
        lines.push(`  --heading-${order}-font-weight: ${size.fontWeight};`);
      }
      if (size.lineHeight !== undefined) {
        lines.push(`  --heading-${order}-line-height: ${size.lineHeight};`);
      }
    }
  }
}

function emitDarkTokenLines(
  lines: string[],
  dark: PartialThemeTokens,
  emitCompanion: boolean,
): void {
  if (dark.colors) {
    for (const [family, scale] of Object.entries(dark.colors).sort(byKey)) {
      for (const [shade, value] of Object.entries(scale ?? {}).sort(byKey)) {
        if (value !== undefined) {
          lines.push(`  --color-${family}-${shade}: ${value};`);
          if (emitCompanion) {
            const bare = stripHslWrapper(value);
            if (bare !== null) {
              lines.push(`  --__hsl-color-${family}-${shade}: ${bare};`);
            }
          }
        }
      }
    }
  }

  if (dark.radius) {
    for (const [key, value] of Object.entries(dark.radius).sort(byKey)) {
      if (value !== undefined) lines.push(`  --radius-${key}: ${value};`);
    }
  }

  if (dark.spacing) {
    for (const [key, value] of Object.entries(dark.spacing).sort(byKey)) {
      if (value !== undefined) lines.push(`  --spacing-${key}: ${value};`);
    }
  }

  if (dark.fontSize) {
    for (const [key, value] of Object.entries(dark.fontSize).sort(byKey)) {
      if (value !== undefined) lines.push(`  --font-size-${key}: ${value};`);
    }
  }

  if (dark.shadow) {
    for (const [key, value] of Object.entries(dark.shadow).sort(byKey)) {
      if (value !== undefined) lines.push(`  --shadow-${key}: ${value};`);
    }
  }

  if (dark.fontFamily) {
    for (const [key, value] of Object.entries(dark.fontFamily).sort(byKey)) {
      if (value !== undefined) lines.push(`  --font-family-${key}: ${value};`);
    }
  }

  if (dark.fontWeight) {
    for (const [key, value] of Object.entries(dark.fontWeight).sort(byKey)) {
      if (value !== undefined) lines.push(`  --font-weight-${key}: ${value};`);
    }
  }

  if (dark.lineHeight) {
    for (const [key, value] of Object.entries(dark.lineHeight).sort(byKey)) {
      if (value !== undefined) lines.push(`  --line-height-${key}: ${value};`);
    }
  }

  if (dark.breakpoint) {
    for (const [key, value] of Object.entries(dark.breakpoint).sort(byKey)) {
      if (value !== undefined) lines.push(`  --breakpoint-${key}: ${value};`);
    }
  }

  if (dark.heading) {
    if (dark.heading.textWrap !== undefined) {
      lines.push(`  --heading-text-wrap: ${dark.heading.textWrap};`);
    }
    if (dark.heading.sizes) {
      for (const [order, size] of Object.entries(dark.heading.sizes).sort(byKey)) {
        if (size === undefined) continue;
        if (size.fontSize !== undefined) {
          lines.push(`  --heading-${order}-font-size: ${size.fontSize};`);
        }
        if (size.fontWeight !== undefined) {
          lines.push(`  --heading-${order}-font-weight: ${size.fontWeight};`);
        }
        if (size.lineHeight !== undefined) {
          lines.push(`  --heading-${order}-line-height: ${size.lineHeight};`);
        }
      }
    }
  }
}

function emitSemanticLines(lines: string[], theme: ResolvedTheme): void {
  for (const [key, ref] of Object.entries(theme.semantic.text).sort(byKey)) {
    lines.push(`  --text-${key}: ${semanticToVar(ref)};`);
  }

  for (const [key, ref] of Object.entries(theme.semantic.surface).sort(byKey)) {
    lines.push(`  --surface-${key}: ${semanticToVar(ref)};`);
  }

  for (const [key, ref] of Object.entries(theme.semantic.border).sort(byKey)) {
    lines.push(`  --border-${key}: ${semanticToVar(ref)};`);
  }

  if (theme.semantic.accent) {
    for (const [key, ref] of Object.entries(theme.semantic.accent).sort(byKey)) {
      lines.push(`  --accent-${key}: ${semanticToVar(ref)};`);
    }
  }
}

function semanticToVar(ref: string): string {
  // 'colors.neutral.500' -> 'var(--color-neutral-500)'
  // 'radius.md' -> 'var(--radius-md)'
  const parts = ref.split('.');
  if (parts[0] === 'colors' && parts.length === 3) {
    return `var(--color-${parts[1]}-${parts[2]})`;
  }
  if (parts[0] === 'radius' && parts.length === 2) {
    return `var(--radius-${parts[1]})`;
  }
  if (parts[0] === 'spacing' && parts.length === 2) {
    return `var(--spacing-${parts[1]})`;
  }
  if (parts[0] === 'fontSize' && parts.length === 2) {
    return `var(--font-size-${parts[1]})`;
  }
  return ref;
}

function byKey([a]: [string, unknown], [b]: [string, unknown]): number {
  return a.localeCompare(b);
}

/**
 * Extracts bare HSL components from an `hsl(...)` wrapped color string.
 *   'hsl(221.2 83.2% 53.3%)'        → '221.2 83.2% 53.3%'
 *   'hsl(221.2, 83.2%, 53.3%)'      → '221.2, 83.2%, 53.3%'  (legacy syntax)
 *   'hsl(221 83% 53% / 0.5)'        → '221 83% 53% / 0.5'
 *
 * Returns `null` for non-hsl values (rgb, hex, named colors, var(), currentColor, etc.)
 * — those values can't usefully participate in Tailwind's <alpha-value> pattern.
 *
 * The `--__hsl-color-X-Y` companion var lets consumers use
 * `hsl(var(--__hsl-color-X-Y) / 0.5)` for translucency and lets Tailwind's
 * alpha-value utility classes work via `hsl(var(--__hsl-color-X-Y) / <alpha-value>)`.
 * The canonical wrapped var (`--color-X-Y`) remains the default for direct
 * CSS consumption. The `--__hsl-` prefix (rather than a `-hsl` suffix) keeps
 * the companions out of the `--color-` autocomplete namespace.
 */
function stripHslWrapper(value: string): string | null {
  const match = value.match(/^hsl\((.*)\)$/i);
  return match && match[1] !== undefined ? match[1].trim() : null;
}
