import type { ResolvedTheme } from '@soribashi/theme';

const HEADER = `/* auto-generated by @soribashi/codegen — do not edit manually */`;

/**
 * Emits a Tailwind v4 `@theme` block from the soribashi theme.
 *
 * In Tailwind v4, CSS is the source of truth for tokens — utility classes
 * are generated automatically from `@theme { --color-xxx: ...; }` blocks.
 */
export function emitTailwindV4(theme: ResolvedTheme): string {
  const lines: string[] = [HEADER, ''];
  lines.push('@theme {');

  for (const [family, scale] of Object.entries(theme.tokens.colors).sort(byKey)) {
    for (const [shade, value] of Object.entries(scale).sort(byKey)) {
      lines.push(`  --color-${family}-${shade}: ${value};`);
    }
  }

  for (const [key, value] of Object.entries(theme.tokens.radius).sort(byKey)) {
    lines.push(`  --radius-${key}: ${value};`);
  }

  for (const [key, value] of Object.entries(theme.tokens.spacing).sort(byKey)) {
    lines.push(`  --spacing-${key}: ${value};`);
  }

  for (const [key, value] of Object.entries(theme.tokens.fontSize).sort(byKey)) {
    lines.push(`  --font-size-${key}: ${value};`);
  }

  if (theme.tokens.fontFamily) {
    for (const [key, value] of Object.entries(theme.tokens.fontFamily).sort(byKey)) {
      lines.push(`  --font-family-${key}: ${value};`);
    }
  }

  if (theme.tokens.fontWeight) {
    for (const [key, value] of Object.entries(theme.tokens.fontWeight).sort(byKey)) {
      lines.push(`  --font-weight-${key}: ${value};`);
    }
  }

  if (theme.tokens.lineHeight) {
    for (const [key, value] of Object.entries(theme.tokens.lineHeight).sort(byKey)) {
      lines.push(`  --line-height-${key}: ${value};`);
    }
  }

  if (theme.tokens.shadow) {
    for (const [key, value] of Object.entries(theme.tokens.shadow).sort(byKey)) {
      lines.push(`  --shadow-${key}: ${value};`);
    }
  }

  if (theme.tokens.breakpoint) {
    for (const [key, value] of Object.entries(theme.tokens.breakpoint).sort(byKey)) {
      lines.push(`  --breakpoint-${key}: ${value};`);
    }
  }

  lines.push('}');

  return `${lines.join('\n')}\n`;
}

function byKey([a]: [string, unknown], [b]: [string, unknown]): number {
  return a.localeCompare(b);
}
