import type {
  PartialThemeTokens,
  ResolvedTheme,
  SemanticSurfaceValue,
  ThemeTokens,
} from '@soribashi/theme';
import { emitLayerDeclaration } from './emit-layer.ts';
import { emitPropertyRegistrations } from './emit-property.ts';
import { emitVisibilityUtilities } from './emit-visibility.ts';
import { removeDefaultVariables } from './remove-default-variables.ts';
import type { EmitCssOptions } from './types.ts';

const HEADER = '/* auto-generated by @soribashi/codegen — do not edit manually */';

// The visibility utilities' `!important` is a spec requirement (see
// emit-visibility.ts's doc comment), not an oversight, so the generated file
// suppresses biome's noImportantStyles rule for itself instead of growing
// the repo's warning baseline by one per !important declaration (20, for the
// default theme's 7 breakpoints plus the light/dark helpers). This MUST be
// the file-wide `biome-ignore-all` form, not a block-level `biome-ignore`
// placed before the @layer: a block-level suppression does not propagate
// into nested rules inside the layer and leaves an unused-suppression
// warning of its own. It also MUST be the very first line of the emitted
// file: biome only honors `biome-ignore-all` at the top of the file.
const SUPPRESS_IMPORTANT_LINT_LINE =
  '/* biome-ignore-all lint/complexity/noImportantStyles: visibility utilities require !important to beat recipe CSS and inline style props (spec requirement) */';

/**
 * Emits the soribashi theme as a CSS file with custom properties for the
 * configured scope and dark mode selectors.
 */
export function emitCss(theme: ResolvedTheme, opts: EmitCssOptions = {}): string {
  // Single source of truth for whether this emit includes the utilities
  // layer: reused both for building the layer body below and for deciding
  // whether the top-of-file lint suppression is warranted (nothing to
  // suppress when utilities are off, e.g. codegen-tenants.ts's scoped emits).
  const utilitiesEnabled = opts.utilities !== false;
  const effectiveTheme = opts.removeDefaultVariables ? removeDefaultVariables(theme) : theme;
  const additions = opts.cssVariablesResolver
    ? opts.cssVariablesResolver(effectiveTheme)
    : undefined;

  if (opts.removeDefaultVariables) {
    const removed = countEmittedTokenVars(theme) - countEmittedTokenVars(effectiveTheme);
    if (removed > 0) {
      // Nothing in soribashi ships a baseline stylesheet (no equivalent of
      // @mantine/core/styles.css), so deduped output is broken unless the
      // consumer provides one. Warn loudly until that story exists.
      console.warn(
        `[soribashi] removeDefaultVariables removed ${removed} variable(s) that match the soribashi defaults. The generated CSS is NOT self-contained: a baseline stylesheet defining the soribashi default variables must be loaded before it, or the removed variables will be undefined at runtime.`,
      );
    }
  }

  // Everything token-shaped — the root scope, the dark flip, any per-scope
  // additions, and the @property registrations — lands in the
  // soribashi.tokens layer. Scope blocks are themselves token declarations
  // (custom-property values for a specific tenant/scope), not component
  // styles, so they belong alongside :root and .dark rather than outside the
  // layer: leaving them unlayered would let their specificity fight a
  // vendoring consumer's own classes, which is exactly the war @layer exists
  // to end. @property registrations are layered too, per emit-property.ts,
  // so a consumer can override a registration by declaring their own
  // unlayered @property for the same name.
  //
  // Visibility utility classes (.sb-hidden-from-*, .sb-visible-from-*,
  // .sb-light-hidden, .sb-dark-hidden; see emit-visibility.ts) are NOT
  // token-shaped: they are component-facing utility rules, not custom-property
  // declarations, so they get their own soribashi.utilities layer below
  // instead of living inside this one.
  const body: string[] = [];

  // :root block
  body.push(`${effectiveTheme.scope} {`);
  body.push('  color-scheme: light;');
  emitTokenLines(body, effectiveTheme.tokens, effectiveTheme.dark);
  emitSemanticLines(body, effectiveTheme);
  if (additions?.root) {
    for (const [key, value] of Object.entries(additions.root)) {
      body.push(`  ${key}: ${value};`);
    }
  }
  body.push('}');

  // Tokens carry both schemes via light-dark(), so the dark selector only has
  // to flip color-scheme. Re-emitting semantic vars here (which the previous
  // implementation required) is no longer necessary: light-dark() resolves at
  // the point of use, so a scoped wrapper flips without any restatement.
  body.push('');
  body.push(`${effectiveTheme.darkMode.selector} {`);
  body.push('  color-scheme: dark;');
  if (additions?.dark) {
    for (const [key, value] of Object.entries(additions.dark)) {
      body.push(`  ${key}: ${value};`);
    }
  }
  body.push('}');

  // Optional scopes — flat blocks for each scope name
  if (additions?.scopes) {
    for (const [scopeName, scopeVars] of Object.entries(additions.scopes)) {
      if (scopeVars.root && Object.keys(scopeVars.root).length > 0) {
        body.push('');
        body.push(`${scopeName} {`);
        for (const [key, value] of Object.entries(scopeVars.root)) {
          body.push(`  ${key}: ${value};`);
        }
        body.push('}');
      }
      if (scopeVars.dark && Object.keys(scopeVars.dark).length > 0) {
        body.push('');
        body.push(`${effectiveTheme.darkMode.selector} ${scopeName} {`);
        for (const [key, value] of Object.entries(scopeVars.dark)) {
          body.push(`  ${key}: ${value};`);
        }
        body.push('}');
      }
    }
  }

  // Typed registrations for non-colour tokens. Colours are never registered:
  // see emit-property.ts for why that would silently break scoped dark mode.
  // Emitted after the :root/.dark rules that use these vars deliberately.
  // @property registration is document-wide, not source-order dependent, so a
  // rule earlier in the file can reference a custom property @property
  // registers later without issue.
  const registrations = emitPropertyRegistrations(effectiveTheme);
  if (registrations.length > 0) {
    body.push('');
    body.push(...registrations);
  }

  const lines: string[] = [];
  if (utilitiesEnabled) {
    lines.push(SUPPRESS_IMPORTANT_LINT_LINE);
  }
  lines.push(
    HEADER,
    '',
    emitLayerDeclaration().trimEnd(),
    '',
    '@layer soribashi.tokens {',
    ...body.map(indentLine),
    '}',
  );

  // Visibility utilities are opt-out (default on) since every builder emits
  // their class names unconditionally; `utilities: false` lets a scoped/
  // tenant emission (see codegen-tenants.ts) skip restating the identical
  // global rules the root theme.css already provides. Reads `theme`, not
  // `effectiveTheme`: see emit-visibility.ts for why the dedup pass must not
  // apply here.
  if (utilitiesEnabled) {
    const utilities = emitVisibilityUtilities(theme);
    lines.push('', '@layer soribashi.utilities {', ...utilities.map(indentLine), '}');
  }

  return `${lines.join('\n')}\n`;
}

function indentLine(line: string): string {
  return line === '' ? '' : `  ${line}`;
}

function countEmittedTokenVars(theme: ResolvedTheme): number {
  const scratch: string[] = [];
  emitTokenLines(scratch, theme.tokens, theme.dark);
  return scratch.length;
}

/**
 * Pairs a light value with its dark override using light-dark(). COLOUR TOKENS
 * ONLY: light-dark() is a <color> production (CSS Color 5), so substituting it
 * into a length/number/keyword property is invalid at computed-value time, and
 * the whole declaration resolves to nothing in BOTH schemes: worse than the
 * old two-block output, where light mode at least worked. Confirmed in
 * Chromium: `CSS.supports('color', 'light-dark(red, blue)')` is true, while
 * `CSS.supports('border-radius', 'light-dark(1px, 2px)')` is false.
 *
 * Unregistered custom properties substitute lazily, so light-dark() resolves
 * against the color-scheme of the element that USES the var, not the one that
 * declares it. That is what lets a single declaration serve a scoped dark
 * wrapper, and it is why colour tokens must never be registered via @property
 * (see emit-property.ts).
 *
 * Every other token family below is emitted bare (light value only). Dark
 * overrides for non-colour tokens are rejected by validateTheme
 * (validate-theme.ts's validateDarkOverrides) before emitCss ever runs, so
 * `tokens.colors` is the only token family that ever calls this with a
 * defined `dark`. `emitSemanticLines` below reuses this same function one
 * layer up, for `semanticTokens.surface`'s optional per-scheme `dark`
 * reference (design-ledger slice): there `light`/`dark` are themselves
 * `var(--color-...)` lookups rather than raw token values, so the emitted
 * light-dark() can nest another light-dark() inside each branch when the
 * underlying colour token also carries its own dark override. Confirmed in
 * Chromium that nesting resolves correctly (each occurrence independently
 * against the color-scheme of the consuming element).
 */
function pairValue(light: string, dark: string | undefined): string {
  return dark === undefined ? light : `light-dark(${light}, ${dark})`;
}

function emitTokenLines(lines: string[], tokens: ThemeTokens, dark: PartialThemeTokens): void {
  for (const [family, scale] of Object.entries(tokens.colors).sort(byKey)) {
    for (const [shade, value] of Object.entries(scale).sort(byKey)) {
      const darkValue = dark.colors?.[family]?.[shade];
      lines.push(`  --color-${family}-${shade}: ${pairValue(value, darkValue)};`);
    }
  }

  for (const [key, value] of Object.entries(tokens.radius).sort(byKey)) {
    lines.push(`  --radius-${key}: ${value};`);
  }

  for (const [key, value] of Object.entries(tokens.spacing).sort(byKey)) {
    lines.push(`  --spacing-${key}: ${value};`);
  }

  for (const [key, value] of Object.entries(tokens.fontSize).sort(byKey)) {
    lines.push(`  --font-size-${key}: ${value};`);
  }

  if (tokens.fontFamily) {
    for (const [key, value] of Object.entries(tokens.fontFamily).sort(byKey)) {
      lines.push(`  --font-family-${key}: ${value};`);
    }
  }

  if (tokens.fontWeight) {
    for (const [key, value] of Object.entries(tokens.fontWeight).sort(byKey)) {
      lines.push(`  --font-weight-${key}: ${value};`);
    }
  }

  if (tokens.lineHeight) {
    for (const [key, value] of Object.entries(tokens.lineHeight).sort(byKey)) {
      lines.push(`  --line-height-${key}: ${value};`);
    }
  }

  if (tokens.shadow) {
    for (const [key, value] of Object.entries(tokens.shadow).sort(byKey)) {
      lines.push(`  --shadow-${key}: ${value};`);
    }
  }

  if (tokens.breakpoint) {
    for (const [key, value] of Object.entries(tokens.breakpoint).sort(byKey)) {
      lines.push(`  --breakpoint-${key}: ${value};`);
    }
  }

  if (tokens.zIndex) {
    for (const [key, value] of Object.entries(tokens.zIndex).sort(byKey)) {
      lines.push(`  --z-index-${key}: ${value};`);
    }
  }

  if (tokens.heading) {
    if (tokens.heading.textWrap !== undefined) {
      lines.push(`  --heading-text-wrap: ${tokens.heading.textWrap};`);
    }
    for (const [order, size] of Object.entries(tokens.heading.sizes).sort(byKey)) {
      lines.push(`  --heading-${order}-font-size: ${size.fontSize};`);
      if (size.fontWeight !== undefined) {
        lines.push(`  --heading-${order}-font-weight: ${size.fontWeight};`);
      }
      if (size.lineHeight !== undefined) {
        lines.push(`  --heading-${order}-line-height: ${size.lineHeight};`);
      }
    }
  }
}

function emitSemanticLines(lines: string[], theme: ResolvedTheme): void {
  for (const [key, ref] of Object.entries(theme.semanticTokens.text).sort(byKey)) {
    lines.push(`  --text-${key}: ${semanticToVar(ref)};`);
  }

  for (const [key, raw] of Object.entries(theme.semanticTokens.surface).sort(byKey)) {
    const pair = resolveSurfacePair(raw);
    // Reuses tokens.colors' own light/dark pairing mechanism one layer up:
    // `pair.dark` absent emits the SAME bare `var(...)` this slot always has
    // (pairValue's no-op branch), so every existing string-form and
    // `{value, foreground}` theme is byte-for-byte unaffected. When present,
    // this is TWO different semantic references (not one reference's own
    // light/dark colour pair), so the emitted light-dark() can itself nest
    // another light-dark() inside each branch (from the underlying colour
    // token's own dark override, if any) — verified in Chromium to resolve
    // correctly: each nested light-dark() call resolves independently
    // against the color-scheme of the element consuming the property.
    const darkVar = pair.dark !== undefined ? semanticToVar(pair.dark) : undefined;
    lines.push(`  --surface-${key}: ${pairValue(semanticToVar(pair.value), darkVar)};`);
    if (pair.foreground !== undefined) {
      lines.push(`  --surface-${key}-foreground: ${semanticToVar(pair.foreground)};`);
    }
  }

  for (const [key, ref] of Object.entries(theme.semanticTokens.border).sort(byKey)) {
    lines.push(`  --border-${key}: ${semanticToVar(ref)};`);
  }

  if (theme.semanticTokens.accent) {
    for (const [key, ref] of Object.entries(theme.semanticTokens.accent).sort(byKey)) {
      lines.push(`  --accent-${key}: ${semanticToVar(ref)};`);
    }
  }
}

interface SurfacePair {
  value: string;
  dark?: string;
  foreground?: string;
}

function resolveSurfacePair(raw: SemanticSurfaceValue): SurfacePair {
  if (typeof raw === 'string') {
    return { value: raw };
  }
  return {
    value: raw.value,
    dark: raw.dark,
    foreground: raw.foreground,
  };
}

function semanticToVar(ref: string): string {
  // 'colors.neutral.500' -> 'var(--color-neutral-500)'
  // 'radius.md' -> 'var(--radius-md)'
  const parts = ref.split('.');
  if (parts[0] === 'colors' && parts.length === 3) {
    return `var(--color-${parts[1]}-${parts[2]})`;
  }
  if (parts[0] === 'radius' && parts.length === 2) {
    return `var(--radius-${parts[1]})`;
  }
  if (parts[0] === 'spacing' && parts.length === 2) {
    return `var(--spacing-${parts[1]})`;
  }
  if (parts[0] === 'fontSize' && parts.length === 2) {
    return `var(--font-size-${parts[1]})`;
  }
  return ref;
}

function byKey([a]: [string, unknown], [b]: [string, unknown]): number {
  return a.localeCompare(b);
}
